### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by ferreirajackson** [davealbert/cbwa#2]
erro 1

**Comment by ferreirajackson** [comment]
fiz alteração, foi consertado?

**Comment by ferreirajackson** [comment]
não, mas o que eu fiz consertou!

**Comment by ferreirajackson** [comment]
erro2

**Comment by ferreirajackson** [comment]
esse é novo mas já resolvi

**Comment by davealbert** [comment]
Estou feliz que você consertou! @ferreirajackson 😁

**Comment by ferreirajackson** [comment]
thanks @davealbert hahahahahaha
